ScripterOG/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('about_us/', views.about_us, name='about_us'),
path('document/', views.view_document, name='view_document'),

    path('password_reset/', PasswordResetView.as_view(
            template_name='accounts/reset_password.html',
            success_url='done/',
            email_template_name='accounts/reset_password_email.html'),
         name='password_reset'),

    path('password_reset/done/', PasswordResetDoneView.as_view(
            template_name='accounts/reset_password_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
            template_name='accounts/reset_password_confirm.html',
            success_url='/'),
         name='password_reset_confirm'),

    path('reset/done/', PasswordResetCompleteView.as_view(
            template_name='accounts/reset_password_complete.html'),
        name='password_reset_complete')

]
'''
    path('password_reset/', PasswordResetView.as_view(template_name='accounts/reset_password.html'),
         name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete')
    '''

ScripterOG/scripter/urls.py
from django.contrib import admin
from django.urls import path, include
from scripter import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ScripterOG/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.

class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset()#.filter(city='kolk')

class UserProfile(models.Model):
    # User test information (Not production fields)
    objects = models.Manager()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)
    current_upload = models.FileField(upload_to='uploads/', blank=True)
    previous_upload = models.FileField(upload_to='uploads/', blank=True)
    upload_changes = models.FileField(upload_to='uploads/', blank=True)

    test = UserProfileManager() #test custom model manager query

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])



post_save.connect(create_profile, sender=User)

ScripterOG/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)


    class Meta:
        model = User
        fields = ['username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2']

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']


        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):


    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password'
        ]
        #exclude = {}

ScripterOG/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash


# Create your views here.
def home(request):
    return render(request, 'accounts/home.html')

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:home'))
    else:
        form = RegistrationForm()

    args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('view_profile'))

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('view_profile'))
        else:
            return redirect(reverse('change_password'))
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)


def about_us(request):
    return render(request, 'accounts/about_us.html')

def view_document(request):
    return render(request, 'accounts/DocumentDisplay.html')



ScripterOG/scripter/views.py
from django.shortcuts import redirect
from django.urls import reverse


def login_redirect(request):
    return redirect(reverse('accounts:login'))

ScripterOG/accounts/templates/accounts/DocumentDisplay.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Script - Demo</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../static/accounts/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../static/accounts/css/simple-sidebar.css" rel="stylesheet">

	<link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
              crossorigin="anonymous">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

	<!-- To Toggle Sidebar - <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>-->
	<style>
		button {
			background:none;
			color: gray;
			border:none; 
			padding:0;
			font: inherit;
			/*border is optional*/
			cursor: pointer;
		}
		button:hover{
			color: #fff;
			background: rgba(255,255,255,0.2);
		}
		button:focus{
			outline: none;
		}
		.noHover{
			pointer-events: none;
		}
	</style>
</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="{% url 'accounts:home' %}" style="font-size: 150%;">Scripter <img src="../../static/accounts/img/Scripter_Logo.png" width= "50px" class="rounded"></img></a>
                </li>
				<br>
                <li>
					<button onclick="getCurrent()" class="noHover" id="Current" style="font-size: 150%;">View Current Draft</button>
                </li>
                <li>
					<button onclick="getPrevious()" id="Previous" style="font-size: 150%;">View Last Draft</button>
                </li>
                <li>
					<button onclick="getChanges()" id="Changes" style="font-size: 150%;">View Changes</button>
                </li>
            </ul>
			
		</div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper" style="background-color: black;">
            <div class="container-fluid" style="background-color: black;">
                
				<!-- <div class="row align-items-start rounded" style="background-color: white;">
                    <div class="col-lg-12">
						<br>
						<hl style="font-size: 250%;">Statistics</h1>
						<br>
						<br>
					</div>
				</div>

				-->

				<br>
					<label for="file" style="color: white; font-size: 150%;">Upload a new edit...</label>
					<input type="file" id="file" accept="application/pdf" onfocus="this.value=''" style="color: white;">
				<br>
				<div class="row align-items-end">
				    <div class="col-lg-12 rounded" style="background-color: white;">
						<br>
						<h1 style="font-size: 250%; color: black;">Demo Script</h1>
						<br>
                        <embed id="pdfDisplay" src="https://s3.amazonaws.com/scripter-project/current.pdf" width="100%" height="1200" type='application/pdf'>
					</div>
				</div>
            </div>
        </div>


        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../../static/accounts/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../static/accounts/js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

	<script>
	function getCurrent(){
		document.getElementById("pdfDisplay").src = "https://s3.amazonaws.com/scripter-project/current.pdf";
		document.getElementById("Current").classList.add("noHover");
		document.getElementById("Previous").classList.remove("noHover");
		document.getElementById("Changes").classList.remove("noHover");
	}
	</script>

	<script>
	function getPrevious(){
		document.getElementById("pdfDisplay").src = "https://s3.amazonaws.com/scripter-project/previous.pdf";
		document.getElementById("Current").classList.remove("noHover");
		document.getElementById("Previous").classList.add("noHover");
		document.getElementById("Changes").classList.remove("noHover");
	}
	</script>

	<script>
	function getChanges(){
		document.getElementById("pdfDisplay").src = "https://s3.amazonaws.com/scripter-project/difference.pdf";
		document.getElementById("Current").classList.remove("noHover");
		document.getElementById("Previous").classList.remove("noHover");
		document.getElementById("Changes").classList.add("noHover");
	}
	</script>

</body>

</html>

ScripterOG/accounts/templates/accounts/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About Us{% endblock %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>Meet the Team</h1>
        <p>This project is divided among four Computer Science students at Cal Poly Pomona.</p>
        <hr class="my-4">
        <p>This idea was came about from the idea of simplifying movie scripts and version control.</p>
        <p>
            <a class="btn btn-primary btn-lg btn-success" href="https://github.com/PolyGenesis/Scripter" role="button">Team GitHub</a>
        </p>
    </div>
</div>

<div class="row">
      <div class="col-6 text-center">
          <div class="card mxy-4" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'team_image/testbio.png' %}" alt="Card image cap">
            <div class="card-body text-center">
                <h5 class="card-title">Michael Nguyen</h5>
                <p>FrontEnd Developer</p>
            </div>
          </div>
      </div>

      <div class="col-6 text-center">
          <div class="card mxy-4" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'team_image/testbio.png' %}" alt="Card image cap">
            <div class="card-body text-center">
                <h5 class="card-title">Thana Sithisombath</h5>
                <p>FrontEnd Developer</p>
            </div>
          </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-3 align-center">
          <div class="card mxy-4" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'team_image/testbio.png' %}" alt="Card image cap">
            <div class="card-body text-center">
                <h5 class="card-title">Chris Villegas</h5>
                <p>BackEnd Developer</p>
            </div>
          </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-3 align-center">
          <div class="card mxy-4" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'team_image/testbio.png' %}" alt="Card image cap">
            <div class="card-body text-center">
                <h5 class="card-title">Michael Ortega</h5>
                <p>BackEnd Developer</p>
            </div>
          </div>
      </div>

      </div>
</div>


{% endblock %}

ScripterOG/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block title%}Change Password{% endblock %}

{% block body %}
<br>
<div class="container rounded white shadow">
    <br>
	<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

ScripterOG/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block title %}Edit Profile{% endblock %}

{% block body %}
<br>
<div class="container rounded white shadow">
	<br>
	<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>
{% endblock %}

ScripterOG/accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block body %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'team_image/testbio.png' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'team_image/testbio.png' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'team_image/testbio.png' %}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="jumbotron jumbotron-fluid">
  <h1 class="text-center">Scripter</h1>
  <p class="text-center">Simplifying Version Control for Text</p>
  <hr class="my-4">
  <p class="text-center">Start uploading any text documents and let Scripter analyze and locate changes made between old and new versions. Identifying changes in large documents have never been easier.</p>
  <div class="col-12 text-center">
    <a class="btn btn-primary btn-lg btn-success" href="login/" role="button">Upload Now</a>
  </div>
</div>

{% endblock %}

ScripterOG/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login Page{% endblock %}

{% block body %}
<br>
<div class="container rounded white shadow">
    <br>
    <h2>Login</h2>
    <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <br>
</div>
{% endblock %}

ScripterOG/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}Logged Out{% endblock %}

{% block body %}
<br>
<div class="container rounded white shadow">
    <br>
    <h1>Logged Out</h1>
    <p>
        You have logged out
    </p>
    <br>
</div>
{% endblock %}

ScripterOG/accounts/templates/accounts/projects.html
{% extends 'base.html' %}

{% block title %}Projects{% endblock %}

{% block body %}
<br>
<div class="container rounded white shadow center-div">
	<br>
	<h1>Projects</h1>
	</br>
        <ul class="center">
            <li><a href="{{ user.userprofile.current_upload.url }}" class="button rounded shadow linkButton">View Current Project</a></li>
	    <li><a href="{{ user.userprofile.previous_upload.url }}" class="button rounded shadow linkButton">View Last Draft</a></li>
	    <li><a href="{{ user.userprofile.upload_changes.url }}" class="button rounded shadow linkButton">View Difference</a></li>
        </ul>
        <br>
</div>
{% endblock %}



ScripterOG/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register Page{% endblock %}

{% block body %}
<br>
<div class="container rounded white shadow">
	<br>
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit">Submit</button>
    </form>
	<br>
</div>
<br>
{% endblock %}

ScripterOG/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block title %}Reset Password{% endblock %}

{% block body %}
<br>
<div class="container rounded white shadow">
    <br>
    <h1>Password Reset </h1>
    <p>
        Forgotten your password? Enter your email address below,
        and we'll email instructions for setting a new one.
    </p>
    <h2>Login </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>
    <br>
</div>
{% endblock %}

ScripterOG/accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password Reset Complete</h1>
    <p>
        You have successfully changed your password.
    </p>
</div>
{% endblock %}

ScripterOG/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}


{% block body %}
<div class="container rounded white shadow">
    <h1>Enter a new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>
</div>
{% endblock %}

ScripterOG/accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password Reset Sent</h1>
    <p>
        We sent an email for resetting your password
    </p>
</div>
{% endblock %}

ScripterOG/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

	{% trans "Thanks for using our site!" %}

	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

	{% endautoescape %}

ScripterOG/accounts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial scale=1">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
              crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!--
	<link rel = "stylesheet" href = "../../static/accounts/style.css">
	<link rel = "stylesheet" href = "../../../static/accounts/style.css">
-->
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <br>
        <!-- Navigation Bar -->
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
            <a class="navbar-brand" href="{% url 'accounts:home'%}"><img src="{% static 'team_image/logo.png'%}" height="20px"> Scripter</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsCollapse" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsCollapse">

              {% if user.is_authenticated %}

              <ul class="navbar-nav p-3">
                <li class="nav-item active mr-auto">
                  <a class="nav-link button" href="{% url 'accounts:view_document' %}">Projects</a>
                </li>
                <li class="nav-item active mr-auto">
                  <a class="nav-link button" href="{% url 'accounts:about_us' %}">About Us</a>
                </li>
                <li class="nav-item dropdown mr-auto">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Profile
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'accounts:view_profile' %}">Profile</a>
                        <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
                      <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>
                      <a class="dropdown-item" href="{% url 'accounts:password_reset' %}">Reset Password</a>
                    </div>
                </li>
                <li class="nav-item active ml-auto">
                  <a class="nav-link button" href="{% url 'accounts:logout' %}">Logout<span class="sr-only">(current)</span></a>
                </li>
              </ul>
              {% else %}

              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link button" href="{% url 'accounts:home' %}">Home</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link button" href="{% url 'accounts:about_us' %}">About Us</a>
                </li>
              </ul>
              <form class="form-inline my-2 my-md-0">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                      <a class="nav-link button" href="{% url 'accounts:login' %}">Login</a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link button" href="{% url 'accounts:register' %}">Register</a>
                  </li>
                </ul>
              </form>

              {% endif  %}

            </div>
          </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>


